version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3
    volumes:
      - .:/workspace:cached # Additional bind mount
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    #network_mode: service:db
    networks: 
      - frontend
      - backend

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

  frontend:
    build: 
      context: ./frontend
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Node version: 10, 12, 14
        VARIANT: 14
    #image: node
    volumes: 
      - .:/workspace:cached # Additional bind mount
    command: sleep infinity
    networks: 
      - frontend
      - backend
    # ...
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5500
    ports:
      - 5500:5500
    networks: 
      - backend

volumes:
  postgres-data:
  pgadmin-data:

networks: 
  backend:
    driver: bridge
  frontend:
    driver: bridge

