
###
POST http://localhost:5000/user/ HTTP/1.1
Content-Type: application/json

{
  "email": "test1@email.com",
  "username": "test1",
  "password": "heslo"
}

###
GET  http://localhost:5000/user/ HTTP/1.1

###
GET  http://localhost:5000/user/ HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTY3NjA2NTUsImlhdCI6MTYxNjY3NDI1MCwic3ViIjoxfQ.ZE4tzm1cZrZLcBOmMoOxKL4mO-KRsRwteuuUBjPLrSo

###
GET  http://localhost:5000/user/d11b1aec-54c5-468e-a15d-a25033abc283 HTTP/1.1


###
POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "string",
  "password": "string"
}

###
POST http://localhost:5000/auth/logout HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTY2NzM0NjksImlhdCI6MTYxNjU4NzA2NCwic3ViIjoxfQ.00UIHmEkA1uefQiQmFz7TgDkeB_mBJYAOnIu_qCn-Jg


###
POST http://localhost:5000/osoba/ HTTP/1.1
Content-Type: application/json

{
  "jmeno": "test",
  "prijmeni": "test",
  "osobni_cislo": 1322424,
  "hodnost_id":0
}